name: Build & Deploy

on:
  push:
    branches: [master]

jobs:
  clone-app:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Project
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
      - run: |
          folder=$(ls)
          if echo $folder | grep -c "projects"
          then
            echo "A pasta ja existe!"
          else
            mkdir projects
          fi
        shell: bash

