name: Build & Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJs App
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            mkdir test
            cd test
            git clone git@github.com:msr-software/test-repo.git
            cd test-repo
            npm i
            pm2 start npm --name teste-app -- start
