name: Build & Deploy

on:
  push:
    branches: [master]

jobs:
  clone-app:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Project
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
 
          script: |
            folder=$(ls)
            if echo $folder | grep -c "test-repo"; 
            then 
              echo "Já existe o projeto clonado"; 
            else 
              git clone git@github.com:msr-software/test-repo.git;
              cd test-repo
              ls
            fi
            
          
